#!/bin/bash
project=project.json
sourcedir=$(realpath source)
outdir=$(realpath out)

if [ -n "$1" ]; then
	project=$1
	outdir=$(dirname $1)
fi

echo Transmute.Help: compiling $project...

mkdir "%outdir%"
python3 compile.py $project
if [ $? -ne 0 ]; then
	exit 1
fi

destination=$(realpath $(jq -r .destination $project))

echo
echo Archiving $destination...
pushd $outdir > /dev/null

cp $sourcedir/styles.css $sourcedir/help.js .
tar cvzf help.tar.gz *.html styles.css help.js toc.json
cp $outdir/help.tar.gz "$destination"

popd > /dev/null
echo
echo done!
