; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only.

#define MyAppName "Transmute"
#define MyAppVersion "0.2"
#define MyAppPublisher "Matt Arriola"
#define MyAppURL "https://github.com/marriola/Transmute/"
#define MyAppExeName "Transmute.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".sc"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt
#define DoubleAmp(Value) StringChange(Value, "&", "&&")
#define EscapeConstArgument(Value) StringChange(StringChange(StringChange(Value, "%", "%25"), ",", "%2c"), "}", "%7d")

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{7AF04FAC-F96C-44A9-85A9-B1F9C3BD981D}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={cm:NameAndVersion,{#EscapeConstArgument(MyAppName)},{#EscapeConstArgument(MyAppVersion)}}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the install be done in "64-bit mode" on x64 or Windows 11 on Arm.
; This means it should use the native 64-bit Program Files directory and the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
; Uncomment the following line to use a 64-bit installer.
;SetupArchitecture=x64
ChangesAssociations=yes
DisableProgramGroupPage=yes
LicenseFile=LICENSE
; Uncomment the following line to run in non administrative install mode (install for current user only).
PrivilegesRequired=lowest
;PrivilegesRequiredOverridesAllowed=dialog
OutputBaseFilename=Transmute_{#MyAppVersion}_Setup
SolidCompression=yes
WizardStyle=modern polar

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "bin\Release\net10.0\publish\win-x64\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "bin\Release\net10.0\publish\win-x64\av_libglesv2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "bin\Release\net10.0\publish\win-x64\libHarfBuzzSharp.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "bin\Release\net10.0\publish\win-x64\libonigwrap.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "bin\Release\net10.0\publish\win-x64\libSkiaSharp.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "sample\ipa\1. pie.txt"; DestDir: "{userdocs}\Transmute\sample\ipa"; Flags: ignoreversion
Source: "sample\ipa\1. protogermanic.sc"; DestDir: "{userdocs}\Transmute\sample\ipa"; Flags: ignoreversion
Source: "sample\ipa\2. protogermanic.txt"; DestDir: "{userdocs}\Transmute\sample\ipa"; Flags: ignoreversion
Source: "sample\ipa\2. westgermanic.sc"; DestDir: "{userdocs}\Transmute\sample\ipa"; Flags: ignoreversion
Source: "sample\ipa\3. westgermanic.txt"; DestDir: "{userdocs}\Transmute\sample\ipa"; Flags: ignoreversion
Source: "sample\ipa\3. oldenglish.sc"; DestDir: "{userdocs}\Transmute\sample\ipa"; Flags: ignoreversion
Source: "sample\ipa\sindarin.sc"; DestDir: "{userdocs}\Transmute\sample\ipa"; Flags: ignoreversion
Source: "sample\ipa\sindarin.txt"; DestDir: "{userdocs}\Transmute\sample\ipa"; Flags: ignoreversion
Source: "sample\x-sampa\1. pie.txt"; DestDir: "{userdocs}\Transmute\sample\x-sampa"; Flags: ignoreversion
Source: "sample\x-sampa\1. protogermanic.sc"; DestDir: "{userdocs}\Transmute\sample\x-sampa"; Flags: ignoreversion
Source: "sample\x-sampa\2. protogermanic.txt"; DestDir: "{userdocs}\Transmute\sample\x-sampa"; Flags: ignoreversion
Source: "sample\x-sampa\2. westgermanic.sc"; DestDir: "{userdocs}\Transmute\sample\x-sampa"; Flags: ignoreversion
Source: "sample\x-sampa\3. westgermanic.txt"; DestDir: "{userdocs}\Transmute\sample\x-sampa"; Flags: ignoreversion
Source: "sample\x-sampa\3. oldenglish.sc"; DestDir: "{userdocs}\Transmute\sample\x-sampa"; Flags: ignoreversion
Source: "sample\x-sampa\sindarin.sc"; DestDir: "{userdocs}\Transmute\sample\x-sampa"; Flags: ignoreversion
Source: "sample\x-sampa\sindarin.txt"; DestDir: "{userdocs}\Transmute\sample\x-sampa"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files.

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#DoubleAmp(MyAppName)}}"; Flags: nowait postinstall skipifsilent

